export default function TermsPage() {
  const pageStyle = {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #0f0c29, #302b63, #24243e)",
    color: "white",
    padding: "40px 20px",
  };

  const cardStyle = {
    maxWidth: "900px",
    margin: "0 auto",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "20px",
    padding: "40px",
    backdropFilter: "blur(10px)",
  };

  const headingStyle = {
    fontSize: "42px",
    marginBottom: "20px",
  };

  const subHeadingStyle = {
    fontSize: "24px",
    marginTop: "30px",
    marginBottom: "10px",
    color: "#c4b5fd",
  };

  return (
    <main style={pageStyle}>
      <div style={cardStyle}>
        <h1 style={headingStyle}>Terms of Use</h1>
        <a
  href="/"
  style={{
    color: "#a855f7",
    textDecoration: "none",
    display: "inline-block",
    marginBottom: "20px",
    fontWeight: "bold",
  }}
>
  ← Back to Home
</a>

        <p>Last updated: June 2026</p>

        <p>
          Natural Stupidity™ is a satire and entertainment website. All
          generated content is fictional, humorous, and intentionally
          unreliable.
        </p>

        <h2 style={subHeadingStyle}>No Real Advice</h2>

        <p>
          Content generated by this website should not be treated as
          professional, financial, medical, legal, technical, or personal
          advice.
        </p>

        <h2 style={subHeadingStyle}>User Responsibility</h2>

        <p>
          Users are fully responsible for their own actions and decisions.
          Do not follow advice generated by this website.
        </p>

        <h2 style={subHeadingStyle}>AI Generated Content</h2>

        <p>
          Responses may be generated using artificial intelligence and may be
          inaccurate, absurd, or completely wrong by design.
        </p>

        <h2 style={subHeadingStyle}>Contact</h2>

        <p>
          For questions, contact:
          {" "}
          contact@naturalstupidityapp.com
        </p>
      </div>
    </main>
  );
}